### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'ProactorEventLoop'  (from master)

### ISSUE THREAD

**Issue by nothingmn** [keethesh/UdemyEnrollEverywhere#2]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    loop = asyncio.ProactorEventLoop()
AttributeError: module 'asyncio' has no attribute 'ProactorEventLoop'
sys:1: RuntimeWarning: coroutine 'learnviral_wrapper' was never awaited
sys:1: RuntimeWarning: coroutine 'yofreesamples' was never awaited

**Comment by keethesh** [comment]
May I ask, on what OS are you running it?

**Comment by XingShunlee** [comment]
i also have this problem
