### ISSUE TITLE
Please make this linux compatible

### ISSUE THREAD

**Issue by mmohamedyaser** [keethesh/UdemyEnrollEverywhere#3]
Firstly love your work and dedication.
I was going through the code and found that some of the chrome features were hard-coded.
**Linux does not have google chrome, it only has chromium.**

I changed the code to use firefox. But I still have **unknown reason** error. 
Check the screenshot for more info. Udemy has a new page asking for the billing address before enroll now.
This could be the reason behind the code giving unknown error.

![unknown reason error](https://i.ibb.co/ZgX0qJW/Screenshot-from-2020-09-13-15-30-24-1.jpg)

**Comment by keethesh** [comment]
Hello! Before changing the code so that it uses Firefox, what was the error you were getting?

**Comment by mmohamedyaser** [comment]
I am getting this error.
![Error image](https://i.ibb.co/cXr0bPD/nre.png)

**Comment by keethesh** [comment]
What happens when you change this (around line 76)
```py
opts = chromeOpts()
opts.add_argument(f"user-agent={ua.random}")
prefs = {'profile.managed_default_content_settings.images': 2}  # Disallow images from loading
opts.add_experimental_option("prefs", prefs)
driver = helium.start_chrome("https://www.udemy.com/random_page_that_does_not_exist/",
                             headless=False,
                             options=opts)
driver.add_cookie(
    {'name': 'client_id', 'value': client_id, 'domain': udemy_domain})
driver.add_cookie(
    {'name': 'access_token', 'value': access_token, 'domain': udemy_domain})
helium.go_to("https://www.udemy.com/?persist_locale=&locale=en_US")
if 'upgrade-your-browser' in driver.current_url:
    driver.quit()
else:
    break
```
to this?
```py
try:
    opts = chromeOpts()
    opts.add_argument(f"user-agent={ua.random}")
    prefs = {'profile.managed_default_content_settings.images': 2}  # Disallow images from loading
    opts.add_experimental_option("prefs", prefs)
    driver = helium.start_chrome("https://www.udemy.com/random_page_that_does_not_exist/",
                                 headless=False,
                                 options=opts)
    driver.add_cookie(
        {'name': 'client_id', 'value': client_id, 'domain': udemy_domain})
    driver.add_cookie(
        {'name': 'access_token', 'value': access_token, 'domain': udemy_domain})
    helium.go_to("https://www.udemy.com/?persist_locale=&locale=en_US")
    if 'upgrade-your-browser' in driver.current_url:
        driver.quit()
    else:
        break
except Exception as e:
    print(e)
```

**Comment by mmohamedyaser** [comment]
Same error.
![image](https://user-images.githubusercontent.com/16500261/95768507-825b9f80-0cc7-11eb-8d12-ad31bda446f7.png)
![image](https://user-images.githubusercontent.com/16500261/95768798-f8600680-0cc7-11eb-8c6e-1b4aa803a51a.png)

I was able to over come this by adding the hard-coding the client_id and access_token after line 153 `args = parser.parse_args()`

**Comment by keethesh** [comment]
If you were able to make it work using chrome, it means chrome isn't the issue here. I think that there is an error in the code itself. I'll check and get back to you!
